name: MiEntradita CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Download dependencies with npm
      run: npm install
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
    
    - name: Upload coverage report to Codacy  
      if: success()
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
